version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"